### ISSUE TITLE
bob.io.image fails to compile with jpeg 9.2

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.io.image#7]
Log is available [here](https://circleci.com/gh/conda-forge/bob.io.image-feedstock/5)
Error:
```
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Wno-strict-aliasing -DBOB_EXT_MODULE_PREFIX="bob.io.image" -DBOB_EXT_MODULE_NAME="_library" -DBOB_EXT_ENTRY_NAME=init_library -DBOB_EXT_MODULE_VERSION="2.0.5" -DHAVE_BOOST=1 -DBOOST_VERSION="1.60.0" -DHAVE_LIBPNG=1 -DLIBPNG_VERSION="1.6.17" -DHAVE_BLITZ=1 -DBLITZ_VERSION="0.10" -DHAVE_LIBJPEG=1 -DLIBJPEG_VERSION="9.2" -DHAVE_LIBTIFF=1 -DLIBTIFF_VERSION="4.0.6" -DHAVE_GIFLIB=1 -DGIFLIB_VERSION="5.1.2" -DPY_ARRAY_UNIQUE_SYMBOL=BOB_NUMPY_C_API -DNO_IMPORT_ARRAY=1 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/opt/conda/envs/_build/lib/python2.7/site-packages/bob/blitz/include -I/opt/conda/envs/_build/lib/python2.7/site-packages/bob/extension/include -I/opt/conda/envs/_build/lib/python2.7/site-packages/bob/io/base/include -I/opt/conda/envs/_build/include -I/opt/conda/envs/_build/lib/python2.7/site-packages/bob/core/include -I/opt/conda/envs/_build/include/python2.7 -c bob/io/image/jpeg.cpp -o build/temp.linux-x86_64-2.7/bob/io/image/jpeg.o -std=c++0x -isystem /opt/conda/envs/_build/lib/python2.7/site-packages/numpy/core/include -isystem /opt/conda/envs/_build/include/libpng16 -isystem /opt/conda/envs/_build/include
bob/io/image/jpeg.cpp: In function ‘void im_save(const string&, const bob::io::base::array::interface&)’:
bob/io/image/jpeg.cpp:274:35: error: cannot convert ‘bool’ to ‘boolean’ for argument ‘2’ to ‘void jpeg_start_compress(j_compress_ptr, boolean)’
   jpeg_start_compress(&cinfo, true);
                                   ^
error: command 'gcc' failed with exit status 1
```

possible [solution](http://news.povray.org/povray.unix/thread/%3Cweb.5145947644c9fa6cde1c639f0@news.povray.org%3E/): `replace "true" with "TRUE"`

**Comment by anjos** [comment]
Looks like a good hunch.

**Comment by anjos** [comment]
Please go ahead and modify this to use `TRUE` instead.
